host: 3.110.166.9
port: 8080
# check interval in sec
interval: 1
light_sensor: 4
water_sensor: 25
temp_sensor: 27
# pin2 of motor drive
motor1: 24
# pin7 of motor drive
motot2: 23
unique_id: jySDEMp4ZY
# send data to server in min
send_data: 1
# send heartbeat to server in sec
heart_beat: 30
